name: cts
channels:
  - conda-forge
  - defaults
dependencies:
  - bcrypt=4.1.2
  - beautifulsoup4=4.12.3
  - bleach=6.1.0
  - Django=4.2.11
  - django-cors-headers=4.3.1
  - html5lib=1.1
  - pymongo=4.6.3
  - python-dotenv=1.0.1
  - pytz=2024.1
  - rdkit=2024.3.1
  # - redis
  # - reportlab
  - requests=2.31.0
  - tabulate=0.9.0
  - xhtml2pdf=0.2.6
  - uwsgi=2.0.23
  - pip:
    - django-parsley==0.7