"""
Definitions for CTS acronyms used on the site.
"""

acronyms = [
	["A-G", "Arnot-Gobas method for determining bioconcentration factor in EPI Suite"],
	["API", "Application Programming Interface"],
	["BAF", "Bioaccumulation Factor"],
	["BCF", "Bioconcentration Factor"],
	["BP", "Boiling Point"],
	["CAS", "Chemical Abstracts Service Number"],
	["CE", "Chemical Editor"],
	["CS", "Chemical Speciation"],
	["CSV", "Comma-Separated Values"],
	["CTS", "Chemical Transformation Simulator"],
	["d_ow", "pH-Dependent Octanol/Water Distribution Coefficient"],
	["DTXSID", "DSSTOX Substance Identifier"],
	["EPA", "Environmental Protection Agency"],
	["EPI", "Suite Estimation Program Interface"],
	["GC", "Group Contribution"],
	["HC", "Hierarchical Clustering"],
	["HTML", "Hypertext Markup Language"],
	["ICP", "Inherent Chemical Properties"],
	["InChIKey", "International Chemical Identifier"],
	["IUPAC", "International Union of Pure and Applied Chemistry"],
	["KLOP", "Method for determining octanol/water partition coefficient in ChemAxon using Klopman et al. models (Klopman, G.; Li, Ju-Yun.; Wang, S.; Dimayuga, M., J.Chem.Inf.Comput.Sci., 1994, 34, 752)"],
	["Kow", "Octanol/Water Partition Coefficient"],
	["MLR", "Multiple Linear Regression"],
	["MP", "Melting Point"],
	["MW", "Molecular Weight"],
	["NCCT", "National Center for Computational Toxicology"],
	["NN", "Nearest Neighbor"],
	["OCSPP", "Office of Chemical Safety and Pollution Prevention"],
	["OPPT", "Office of Pollution Prevention and Toxics"],
	["PCP", "Physicochemical Properties"],
	["PDF", "Portable Document Format"],
	["PHYS", "Method for determining octanol/water partition coefficient in ChemAxon based on the PHYSPROP database"],
	["PHYSPROP", "Database of 41,000 chemicals and their properties from SRC, Inc. bundled with EPI Suite"],
	["pKa", "Acid Dissociation Constant"],
	["pKb", "Base Dissociation Constant"],
	["PMN", "Pre-Manufacturing Notification"],
	["QED", "Quantitative Exposure Domain"],
	["QSAR", "Quantitative Structure Activity Relationship"],
	["REG", "Regression method  for determining bioconcentration factor in EPI Suite"],
	["RPS", "Reaction Pathway Simulator"],
	["SM",	"Single Model"],
	["SMILES", "Simplified Molecular-Input Line-Entry System"],
	["SPARC", "SPARC Performs Automated Reasoning in Chemistry"],
	["TEST", "Toxicity Estimation Software Tool"],
	["TSCA", "Toxic Substances Control Act"],
	["VG", "Method for determining octanol/water partition coefficient in ChemAxon derived from Viswanadhan et al. (Viswanadhan, V. N.; Ghose, A. K.; Revankar, G. R.; Robins, R. K., J. Chem. Inf. Comput. Sci., 1989, 29, 163-172)"],
	["VP", "Vapor Pressure"],
	["WATERNT", "Fragment-based QSAR model for determining water solubility in EPI Suite"],
	["WSKOW", "QSAR model for determining water solubility in EPI Suite"],
]

def get_acronyms():
	return acronyms